FROM mcr.microsoft.com/dotnet/sdk:6.0 AS dotnet-sdk

FROM jenkins/jenkins:lts

USER root

COPY --from=dotnet-sdk /usr/share/dotnet /usr/share/dotnet

RUN chown -R jenkins:jenkins /usr/share/dotnet

RUN apt-get update \
    && apt-get install -y libicu-dev

ENV DOTNET_ROOT /usr/share/dotnet
ENV PATH $PATH:$DOTNET_ROOT

USER jenkins