version: '3.4'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.Jenkins
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home