apiVersion: v1
kind: Service
metadata:
    name: dotnet-api-service
    labels:
        app: dotnet-api
spec:
    selector:
        app: dotnet-api
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 80